export const PATHS = {
  start: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  verifyEmail: "/verify-email",
  onboarding: "/onboarding",
  onboardingLevel: "/onboarding/level",
  onboardingLevelQuestion: "/onboarding/level/question",
  onboardingLevelQuestionFly: "/onboarding/level/question/fly",
  onboardingQuestionGoal: "/onboarding/question/goal",
  onboardingResults: "/onboarding/results",
  onboardingDailyGoal: "/onboarding/daily-goal",
  onboardingTrial: "/onboarding/trial",
  onboardingRunLesson: "/onboarding/run-lesson",
  onboardingDemoLessonStub: "/onboarding/demo-lesson-stub",
  onboardingPreCreateProf: "/onboarding/pre-create-profile",
  onboardingCreateProfLater: "/onboarding/create-profile-later",
  home: "/home",
  profile: "/profile",
  admin: "/admin",
};
